clear
close all
clc

idiom = loadjson2table('./output/idiom.json', 'idiom');
initial = loadjson2table('./output/initial.json', 'initial');
final = loadjson2table('./output/final.json', 'final');
tone = loadjson2table('./output/tone.json', 'tone');
attempt = loadjson2table('./output/attempt.json', 'attempt');
time = duration(loadjson('./output/time.json')); % histogram

fig = figure;
ax_initial = subplot(4, 2, [1, 2]);
b_initial = bar( ...
    ax_initial, ...
    reordercats(categorical(initial.initial), initial.initial), ...
    initial.counts ...
    );
text( ...
    ax_initial, b_initial.XEndPoints, b_initial.YEndPoints, string(b_initial.YData), ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'bottom' ...
    );
xlabel("Initial");
ylabel("Frequency");

ax_final = subplot(4, 2, [3, 4]);
b_final = bar( ...
    ax_final, ...
    reordercats(categorical(final.final), final.final), ...
    final.counts ...
    );
text( ...
    ax_final, b_final.XEndPoints, b_final.YEndPoints, string(b_final.YData), ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'bottom' ...
    );
xlabel("Final");
ylabel("Frequency");

ax_tone = subplot(4, 2, 5);
b_tone = bar( ...
    ax_tone, ...
    reordercats(categorical(tone.tone), {'1', '2', '3', '4', '_'}), ...
    tone.counts ...
    );
text( ...
    ax_tone, b_tone.XEndPoints, b_tone.YEndPoints, string(b_tone.YData), ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'bottom' ...
    );
xlabel("Tone");
ylabel("Frequency");

ax_attempt = subplot(4, 2, 6);
b_attempt = bar( ...
    ax_attempt, ...
    reordercats( ...
    categorical(attempt.attempt), ...
    {'1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'} ...
    ), ...
    attempt.counts ...
    );
text( ...
    ax_attempt, b_attempt.XEndPoints, b_attempt.YEndPoints, string(b_attempt.YData), ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'bottom' ...
    );
xlabel("Attempt");
ylabel("Frequency");

ax_time = subplot(4, 2, [7, 8]);
h = histogram(time);
h.NumBins = 20;
h.FaceAlpha = 1;
h.BinWidth = duration('00:00:30');
text( ...
    ax_time, h.BinEdges(2:end)-h.BinWidth/2, h.BinCounts, string(h.BinCounts), ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'bottom' ...
    );
xlabel("Attempt time (minute)");
ylabel("Frequency");
ax_time.XLim = [duration('-00:01:00'), duration('00:24:00')];
ax_time.XTick = duration(0, 0:1:23, 0);
ax_time.XTickLabel = 0:1:23;
% ax_time.YLim = [0, 25];

% 绘制词云
% fig_wc = figure;
% ax_wc = axes(fig_wc);
% wc_idiom = wordcloud( ...
%     idiom, ...
%     idiom.Properties.VariableNames{1}, idiom.Properties.VariableNames{2});
% wc_idiom.Title = '';
% wc_idiom.MaxDisplayWords = 1000;

function data = loadjson2table(file_name, table_name)
data = loadjson( ...
    file_name, ...
    'UseMap', 1, ...
    'Encoding', 'UTF-8' ...
    );

data = table( ...
    data.keys', cell2mat(data.values'), ...
    'VariableNames', {table_name, 'counts'} ...
    );
% sort table
data = sortrows(data, 'counts', 'descend');
end
